version: '3.8'

services:
  node0:
    container_name: avalanchego-subnetevm-node0
    image: ghcr.io/jimmy-yii/avalanchego-subnetevm:v1.12.0_v0.7.0
    volumes:
      - ./data:/data
    network_mode: host
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      - AVALANCHEGO_CHAIN_CONFIG_DIR=/data/chains
      - AVALANCHEGO_NETWORK_ID=fuji
      - AVALANCHEGO_DATA_DIR=/data
      - AVALANCHEGO_PLUGIN_DIR=/plugins/ 
      - AVALANCHEGO_HTTP_PORT=9650
      - AVALANCHEGO_STAKING_PORT=9651
      - AVALANCHEGO_TRACK_SUBNETS=6vLU8FRMJVda5V5xnh1dyaGLZiE94eZ12pXubUpuPLAZaPmAu
      - AVALANCHEGO_HTTP_ALLOWED_HOSTS=*
      - AVALANCHEGO_HTTP_HOST=0.0.0.0
      - AVALANCHEGO_PUBLIC_IP_RESOLUTION_SERVICE=ifconfigme
      - AVALANCHEGO_PARTIAL_SYNC_PRIMARY_NETWORK=true


volumes:
  avalanche-data:
