version: '3.8'

services:
  node0:
    container_name: avalanchego-subnetevm-node0
    image: ghcr.io/jimmy-yii/avalanchego-subnetevm:v1.12.1_v0.7.0
    volumes:
      - ./data:/data
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - 9650:9650
      - 9651:9651
    environment:
      - AVALANCHEGO_CHAIN_CONFIG_DIR=/config
      - AVALANCHEGO_NETWORK_ID=fuji
      - AVALANCHEGO_DATA_DIR=/data
      - AVALANCHEGO_PLUGIN_DIR=/plugins/ 
      - AVALANCHEGO_HTTP_PORT=9650
      - AVALANCHEGO_STAKING_PORT=9651
      - AVALANCHEGO_TRACK_SUBNETS=6vLU8FRMJVda5V5xnh1dyaGLZiE94eZ12pXubUpuPLAZaPmAu
      - AVALANCHEGO_HTTP_ALLOWED_HOSTS=*
      - AVALANCHEGO_HTTP_HOST=0.0.0.0
      - AVALANCHEGO_BOOTSTRAP_IDS=NodeID-v5SPrLFxbXzxyFp78GdKPqjrn7m6UFnN
      - AVALANCHEGO_BOOTSTRAP_IPS=34.231.229.159:9651
      - AVALANCHEGO_PUBLIC_IP_RESOLUTION_SERVICE=ifconfigme
      - AVALANCHEGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVALANCHEGO_STAKING_TLS_KEY_FILE_CONTENT=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0FMOHhiU3htZlpmRzY5b0kKSWVMU3pIQ3J3dU1GTEsxaGt3R0NZYmV6NjZhaFJBTkNBQVFIVlVKUjJSdGNWck5WR2FKb0lkV0kxZkNqMHVpYgpieEpmL1hLQjFtcHBxbGQ2dXFTd1NIRlJDbVN5RmhXenZ5d1JSTlBMUDBaSyt6dXRHb2xMZ1Q0ZAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      - AVALANCHEGO_STAKING_TLS_CERT_FILE_CONTENT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJFRENCdDZBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01BQXdJQmNOT1RreE1qTXhNREF3TURBd1doZ1AKTWpFeU5ERXlNak14TURVMk1qTmFNQUF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFIVlVKUgoyUnRjVnJOVkdhSm9JZFdJMWZDajB1aWJieEpmL1hLQjFtcHBxbGQ2dXFTd1NIRlJDbVN5RmhXenZ5d1JSTlBMClAwWksrenV0R29sTGdUNGRveUF3SGpBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQUsKQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBcUY4ekU0TzAxdVFQUW5jSlpaVi9LZDNLVzFaaXIwM3FHb3dIWFNFNApzd1FDSUFyUWNaY1pxTFE1TW1oTDRpUHZMUnpUbzkrR1R0bTJKOGYvcXFMSjk5T2IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      - BLS_KEY_BASE64=RSQryQRzxSxgX/dfTAXxbnaMy7E1fP1Ee3kBcZTFHMQ=