name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  # Optional: Also trigger on tags
  tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        avalanchego: ["1.12.0"]
        subnetevm: ["0.7.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            AVALANCHEGO_VERSION=${{ matrix.avalanchego }}
            SUBNETEVM_VERSION=${{ matrix.subnetevm }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ matrix.avalanchego }}_v${{ matrix.subnetevm }}
